# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-07 19:35
from __future__ import unicode_literals

import Alldata.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentdate', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(unique=True)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc_mobile', models.CharField(max_length=10, validators=[Alldata.validators.valid_mob])),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_spec', models.CharField(max_length=20)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.DoctorData')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_num', models.IntegerField()),
                ('Locality', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointmentsBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentdate', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('doc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.DoctorData')),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, validators=[Alldata.validators.valid_mob])),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.PatientData')),
            ],
        ),
        migrations.AddField(
            model_name='patientappointmentsbooked',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.PatientData'),
        ),
        migrations.AddField(
            model_name='patientadd',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.PatientData'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='doc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.DoctorData'),
        ),
        migrations.AddField(
            model_name='doctorappointment',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alldata.PatientData'),
        ),
    ]
